# Generated by Django 4.2.11 on 2024-06-26 15:49

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(help_text='Enter a user ID that is 6-32 characters long and contains only letters and numbers.', max_length=32, unique=True, validators=[django.core.validators.MinLengthValidator(6), django.core.validators.MaxLengthValidator(32), django.core.validators.RegexValidator(code='invalid_user_id', message='user_id must be an alphanumeric string.', regex='^[a-zA-Z0-9]+$')])),
                ('user_password', models.CharField(max_length=255)),
                ('user_nikeName', models.CharField(default='默认昵称', max_length=255)),
            ],
        ),
    ]
