# Generated by Django 4.2.11 on 2024-08-16 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiPlatformImplement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='isAdmin',
            field=models.BooleanField(default=False),
        ),
    ]
