# Generated by Django 4.2.11 on 2024-08-14 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiPlatformImplement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditbuyhistory',
            name='price',
            field=models.IntegerField(default=68),
        ),
    ]
