# Generated by Django 4.2.13 on 2024-07-17 14:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiPlatformImplement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='users', validators=[django.core.validators.FileExtensionValidator(['txt', 'pdf', 'jpg', 'png'])], verbose_name='用户头像'),
        ),
    ]
