# Generated by Django 4.2.11 on 2024-06-27 05:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('aiPlatformImplement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='chatHistoryIndex',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aiPlatformImplement.useraccount')),
            ],
        ),
        migrations.CreateModel(
            name='chatHistoryContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.BooleanField(default=False)),
                ('chatContent', models.TextField()),
                ('title', models.TextField()),
                ('messageID', models.IntegerField(default=0)),
                ('indexID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aiPlatformImplement.chathistoryindex')),
            ],
        ),
    ]
