# Generated by Django 4.2.13 on 2024-07-11 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aiPlatformImplement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='prompt',
            fields=[
                ('pid', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('intro', models.CharField(max_length=2000)),
                ('text', models.TextField()),
                ('flexibility', models.FloatField(default=0)),
                ('randomness', models.FloatField(default=0)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aiPlatformImplement.useraccount')),
            ],
        ),
        migrations.CreateModel(
            name='rank',
            fields=[
                ('rid', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('ranking', models.FloatField(default=0)),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aiPlatformImplement.prompt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aiPlatformImplement.useraccount')),
            ],
        ),
    ]
