# Generated by Django 4.2.13 on 2024-07-13 18:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aiPlatformImplement", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="return_url",
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
