# Generated by Django 4.2.13 on 2024-08-15 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiPlatformImplement', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='ai',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
