# Generated by Django 4.2.13 on 2024-07-11 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiPlatformImplement', '0002_alter_ai_level_alter_ai_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='talk',
            name='followflag',
            field=models.IntegerField(default=0),
        ),
    ]
