# Generated by Django 4.2.13 on 2024-07-17 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiPlatformImplement', '0002_useraccount_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='file',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='avaterindex',
            field=models.IntegerField(default=0),
        ),
    ]
