# Generated by Django 4.2.11 on 2024-07-16 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aiPlatformImplement', '0002_promptaccess_modelaccess'),
    ]

    operations = [
        migrations.CreateModel(
            name='creditHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credits', models.IntegerField(default=5, null=True)),
                ('descriptionText', models.TextField(default='变化', max_length=80)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aiPlatformImplement.useraccount')),
            ],
        ),
    ]
