# Generated by Django 4.2.11 on 2024-08-14 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aiPlatformImplement', '0002_creditbuyhistory_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelaccess',
            name='timesLeft',
        ),
        migrations.AddField(
            model_name='creditbuyhistory',
            name='settled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='modelaccess',
            name='expireTime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='modelHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventTime', models.DateTimeField(auto_now=True)),
                ('modifyTime', models.IntegerField(default=30)),
                ('engine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aiPlatformImplement.aiengine')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aiPlatformImplement.useraccount')),
            ],
        ),
    ]
