# Generated by Django 4.2.11 on 2024-08-01 13:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('aiPlatformImplement', '0003_remove_useraccount_file_useraccount_avaterindex'),
    ]

    operations = [
        migrations.AddField(
            model_name='chathistoryindex',
            name='createTime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
