# Generated by Django 4.2.11 on 2024-07-16 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiPlatformImplement', '0003_credithistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='credithistory',
            name='payed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='promptaccess',
            name='payed',
            field=models.BooleanField(default=False),
        ),
    ]
