# Generated by Django 4.2.13 on 2024-08-15 08:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("aiPlatformImplement", "0002_order"),
        ("aiPlatformImplement", "0003_remove_modelaccess_timesleft_and_more"),
    ]

    operations = []
