# Generated by Django 4.2.11 on 2024-07-16 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aiPlatformImplement', '0004_credithistory_payed_promptaccess_payed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credithistory',
            name='payed',
        ),
        migrations.AddField(
            model_name='modelaccess',
            name='payed',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='creditBuyHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credits', models.IntegerField(default=5, null=True)),
                ('payed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aiPlatformImplement.useraccount')),
            ],
        ),
    ]
