# Generated by Django 4.2.13 on 2024-08-15 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("aiPlatformImplement", "0004_merge_20240815_1631"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="note",
            field=models.CharField(blank=True, default="无", max_length=100),
        ),
        migrations.AlterField(
            model_name="order",
            name="operation",
            field=models.CharField(blank=True, default="充值", max_length=100),
        ),
        migrations.AlterField(
            model_name="order",
            name="user",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="aiPlatformImplement.useraccount",
            ),
            preserve_default=False,
        ),
    ]
