# Generated by Django 4.2.11 on 2024-08-15 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiPlatformImplement', '0005_order_note_alter_order_operation_alter_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelaccess',
            name='expireTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
