# Generated by Django 4.2.13 on 2024-06-30 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aiPlatformImplement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ai',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('owner', models.CharField(max_length=255)),
                ('brief', models.TextField()),
                ('time', models.DateField(auto_now=True)),
                ('marks', models.IntegerField()),
                ('level', models.IntegerField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aiPlatformImplement.useraccount')),
            ],
        ),
        migrations.CreateModel(
            name='talk',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('follow', models.IntegerField()),
                ('username', models.CharField(max_length=255)),
                ('follownum', models.IntegerField()),
                ('text', models.TextField()),
                ('time', models.DateField(auto_now=True)),
                ('great', models.IntegerField()),
                ('level', models.IntegerField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aiPlatformImplement.useraccount')),
            ],
        ),
        migrations.CreateModel(
            name='favorite',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateField(auto_now=True)),
                ('ai', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aiPlatformImplement.ai')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aiPlatformImplement.useraccount')),
            ],
        ),
    ]
