# Generated by Django 4.2.11 on 2024-07-01 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aiPlatformImplement', '0002_aiengine_chathistoryindex_chathistorycontent_and_more'),
        ('aiPlatformImplement', '1002_ai_talk_favorite'),
    ]

    operations = [
    ]
