# Generated by Django 4.2.11 on 2024-07-01 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aiPlatformImplement', '1003_merge_20240702_0204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='talk',
            old_name='great',
            new_name='greatNum',
        ),
        migrations.AlterField(
            model_name='aiengine',
            name='subname',
            field=models.CharField(default='默认提供,免费使用的轻量Ai引擎', max_length=88),
        ),
        migrations.CreateModel(
            name='great',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('talk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aiPlatformImplement.talk')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aiPlatformImplement.useraccount')),
            ],
        ),
    ]
