# Generated by Django 4.2.11 on 2024-07-01 14:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiPlatformImplement', '1003_merge_20240701_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='user_id',
            field=models.CharField(help_text='Enter a user ID that is 6-32 characters long and contains only letters and numbers.', max_length=32, unique=True, validators=[django.core.validators.MinLengthValidator(6), django.core.validators.MaxLengthValidator(32), django.core.validators.RegexValidator(code='invalid_user_id', message='user_id must be an alphanumeric string.', regex='[a-zA-Z0-9]+')]),
        ),
    ]
