# Generated by Django 4.2.13 on 2024-07-02 18:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aiPlatformImplement", "1004_order"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="order_id",
        ),
        migrations.RemoveField(
            model_name="order",
            name="transaction_content",
        ),
        migrations.AddField(
            model_name="order",
            name="product_id",
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="order",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
