# Generated by Django 4.2.11 on 2024-07-04 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aiPlatformImplement', '1005_remove_order_order_id_and_more'),
        ('aiPlatformImplement', '1006_alter_useraccount_user_id'),
    ]

    operations = [
    ]
