# Generated by Django 4.2.11 on 2024-07-04 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiPlatformImplement', '1007_merge_20240704_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='user_Credits',
            field=models.IntegerField(default=0),
        ),
    ]
