# Generated by Django 4.2.11 on 2024-07-04 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiPlatformImplement', '1008_useraccount_user_credits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='user_Credits',
            field=models.IntegerField(default=5),
        ),
    ]
